In [2]:
import torch
import torch.nn as nn

In [3]:
input_ids = torch.tensor([2, 3, 5, 1])
print(input_ids)


tensor([2, 3, 5, 1])


In [4]:
vocab_size = 6
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [6]:
print(embedding_layer.weight[3])

tensor([-0.4015,  0.9666, -1.1481], grad_fn=<SelectBackward0>)


In [8]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [9]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


In [18]:
input_index = torch.tensor([2, 5, 4])
print(input_index)

emb_dim = 10
vocab_size = 6

embedding_layer2 = torch.nn.Embedding(vocab_size, emb_dim)
print(embedding_layer2)
print(embedding_layer2.weight)

tensor([2, 5, 4])
Embedding(6, 10)
Parameter containing:
tensor([[ 0.8604,  0.2078,  0.6413,  0.5291,  1.2251,  0.5123, -0.0264, -1.6044,
          1.5446,  1.0394],
        [-0.3804,  0.9701,  0.8243, -0.4808,  0.3678, -0.3318,  1.9431,  0.2169,
         -0.1464, -0.4490],
        [-1.8926,  0.6000,  0.3799, -1.8057,  2.9590,  0.8171,  2.5932, -2.0855,
         -0.8742, -1.3153],
        [-0.7055, -0.3350,  1.1051, -0.5454, -0.2115, -0.2708, -0.0830, -0.2453,
         -0.9124, -1.4065],
        [ 1.3834,  0.0324,  0.0040,  0.3480,  0.7074,  0.3276,  1.0658,  1.4130,
         -1.2445,  0.2227],
        [ 0.8423, -2.4813,  0.6554, -0.1045, -1.1134,  0.5110,  0.3566,  1.8591,
         -0.0425,  0.3271]], requires_grad=True)


In [19]:
print(embedding_layer2(input_index))

tensor([[-1.8926,  0.6000,  0.3799, -1.8057,  2.9590,  0.8171,  2.5932, -2.0855,
         -0.8742, -1.3153],
        [ 0.8423, -2.4813,  0.6554, -0.1045, -1.1134,  0.5110,  0.3566,  1.8591,
         -0.0425,  0.3271],
        [ 1.3834,  0.0324,  0.0040,  0.3480,  0.7074,  0.3276,  1.0658,  1.4130,
         -1.2445,  0.2227]], grad_fn=<EmbeddingBackward0>)
